# Generated by Django 4.2.11 on 2024-12-09 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='user_id',
            new_name='user',
        ),
    ]
