# Generated by Django 4.2.11 on 2024-12-09 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_user_id_account_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='user',
            new_name='user_info',
        ),
    ]
