# Generated by Django 5.1.4 on 2024-12-17 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_user_account_user_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='creator_account',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='account.account'),
        ),
    ]
